feat(docs): upgrade mkdocs/mermaid
linkml/linkml-project-cookiecutter pull request #100
Opened 2024-02-26 19:04 UTC by noelmcloughlin

This PR is to upgrade mkdocs-material and mermaid2 to later versions.

2024-02-26 19:14 UTC, noelmcloughlin commented
Wait for decision on #99 and more testing

2024-02-27 21:22 UTC, noelmcloughlin commented
Seems to work fine. 

 Note: Mermaid dislikes Linkml class names with keywords like "class".  For example, `ontology class` causes syntax error rendering diagrams, but `OntologyClass` does not.

2024-03-13 23:27 UTC, cmungall requested changes
I don't think we should be committing the `mermaid.min.js` itself

2024-08-18 01:00 UTC, noelmcloughlin commented
Hi @cmungall 
I will remove that from this PR and address via https://github.com/linkml/linkml-project-cookiecutter/issues/118

2024-08-18 23:33 UTC, noelmcloughlin commented
Ready for review.

2024-08-19 16:53 UTC, noelmcloughlin commented
Examples for sample "void" schema
Dark mode (Dracula):
![image](https://github.com/user-attachments/assets/0b8b1215-8124-4815-a33a-8bc0090dfdf6)

Normal mode:
![image](https://github.com/user-attachments/assets/596ac7bc-0fa5-4b2d-85d0-7414739908cb)

2025-02-10 15:02 UTC, amc-corey-cox requested changes
This looks like it could be ready to go now. I'm sorry we sat on it for a while. There are couple of conflicts. Would you mind managing those? Then if you could address the palette changes this can go in. If you've already consulted the community on the palette changes just let me know.

2025-02-10 15:02 UTC, amc-corey-cox commented on {{cookiecutter.project_name}}/mkdocs.yml
> +    accent: deep purple
I'm not sure why we're changing the palette here. I don't love the original scheme, and prefer dark mode myself, but I don't think we should make a change like this without consulting our community.

2025-06-10 09:15 UTC, noelmcloughlin commented on {{cookiecutter.project_name}}/mkdocs.yml
> +    accent: deep purple
I have updated, thanks for reviewing.

2025-10-23 15:47 UTC, merged