mkdocs-filter-and-sort
linkml/linkml-project-cookiecutter pull request #99
Opened 2024-02-11 02:06 UTC by plbremer

updated mkdocs.yaml and added .js files such that generated documentation has filter/sort capabilites for tables.

example:
<img width="701" alt="image" src="https://github.com/linkml/linkml-project-cookiecutter/assets/81600274/adc6d39f-e4e9-4ecf-beae-29a1f2089498">

2024-02-13 19:43 UTC, sujaypatil96 requested changes
@plbremer thank you for adding the functionality to sort and filter tables in the generated HTML docs/webpages, it's much appreciated!!

One thing that I'm skeptical about is putting the additional javascript files in the `src/docs/` folder. I don't know if the intention for that folder is that it should contain only markdown, or if it's also okay to put in scripts that are required for building customized documentation.

Feel free to bring this discussion/topic to a LinkML developers call, or if you're unavailable during that time I can bring it up on the next call and let you know what the consensus is. I'll ask if it's okay to put the javascript files in `src/docs/` or if people would prefer we make another new folder at the same level as `docs/` called say `scripts/` which can contain additional scripts which may or may not be limited to javascript (i.e., can include python and so forth as well) and have them be copied over into the destination documentation folder so that mkdocs can look for it.

We may or may not need to update to the `gendoc` Makefile target/rule here depending on what we decide: https://github.com/linkml/linkml-project-cookiecutter/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/Makefile#L195-L197

Another possible concern/caveat is that for some HTML tables we are displaying the contents of that table in a "hierarchially indented" fashion. For example, see this table: https://microbiomedata.github.io/nmdc-schema/#classes

Sorting is pretty straightforward but we haven't yet discussed how sorting should work on a table like this.

2024-02-14 23:14 UTC, cmungall commented
how about https://squidfunk.github.io/mkdocs-material/reference/data-tables/#sortable-tables

2024-02-15 00:57 UTC, plbremer commented
Hi Sujay/Chris,

1) If you could generate a response on my behalf for the `/src/docs` portion, that would be great.
2) I agree that the `make gendoc` command works as is, but might require reworking
3) @cmungall Indeed, I followed that guide to get the sorting working. Then, I roughly applied the same steps to get the filtering working using a different "javascript library".
3 continued) Well, I guess I would defer to the maintainers of LinkML for how the indentation ought to work. One could imagine obsoleting the quandary by only permitting the filtering portion of this PR.

Please let me know your thoughts.

2024-02-26 19:14 UTC, noelmcloughlin commented
Including extra javascript under `src/docs/` is probably okay.  Sandboxed environments cannot retrieve `mermaid` from internet for example: https://github.com/fralau/mkdocs-mermaid2-plugin/issues/64

2024-02-28 16:17 UTC, sierra-moxon commented
I also sometimes have js in the /docs folder - I think its ok.

2024-03-01 23:23 UTC, sujaypatil96 commented
Would it be too much for you to split this work out into two separate PRs @plbremer? The reason I ask is because I know we definitely want to have filtering on tables by default, but what I'm not super sure about is sorting, and that's because of the hierarchically indented table view that I mentioned in my above comment.

2024-03-06 22:36 UTC, plbremer commented
> Would it be too much work for you to split this out into two separate PRs @plbremer? The reason I ask is because I know we definitely want to have filtering on tables by default, but what I'm not super sure about is sorting, and that's because of the hierarchically indented table view that I mentioned in my above comment.

np
https://github.com/linkml/linkml-project-cookiecutter/pull/104
https://github.com/linkml/linkml-project-cookiecutter/pull/105

2025-02-10 15:08 UTC, closed without merging

2025-02-10 15:08 UTC, amc-corey-cox commented
It looks to me like we have two PR's that this PR was split into. One is merged and I'm following up on the other. I am closing this now as I believe it is redundant. Please ping me if you think we still need to have this PR open.